Aptitude Engine beta
kbhat62/AptitudeEngine pull request #3
Opened 2017-05-09 12:58 UTC by Abytecoder

2017-05-09 18:53 UTC, theBuzzyCoder requested changes

2017-05-09 18:53 UTC, smartkarthik commented on main.py
> +@app.route('/')
Add two newline above 
```python
@app.route
```
Everywhere, wherever you have not added newlines after end of function

2017-05-10 12:15 UTC, Abytecoder commented
Added newlines in my recent commit

2017-08-17 19:14 UTC, theBuzzyCoder approved these changes

2017-08-17 19:14 UTC, theBuzzyCoder commented on modules/AptitudeEngine.py
> +def format_solution(sol_dict):
new line

2017-08-17 19:15 UTC, closed without merging

2017-08-17 19:15 UTC, theBuzzyCoder commented
This has been merged to the master branch